export const buildTeamOptionsDropDown = [
  {
    label: "Type",
    options: [
      "bug",
      "dragon",
      "fighting",
      "flying",
      "ghost",
      "grass",
      "ground",
      "poison",
      "psychic",
      "water",
      "dark",
      "ice",
      "electric",
      "fairy",
      "fire",
      "rock",
      "steel",
      "normal",
    ],
  },
];
