export const buildTeamOptionsDropDown = [
  {
    label: "Type",
    options: [
      "Bug",
      "Dragon",
      "Fighting",
      "Flying",
      "Ghost",
      "Grass",
      "Ground",
      "Poison",
      "Psychic",
      "Water",
      "Dark",
      "Ice",
      "Electric",
      "Fairy",
      "Fire",
      "Rock",
      "Steel",
      "Normal",
    ],
  },
  { label: "Evolution", options: ["Fully Evolved", "Not Fully Evolved"] },
  {
    label: "Generation",
    options: [
      "Gen 1",
      "Gen 2",
      "Gen 3",
      "Gen 4",
      "Gen 5",
      "Gen 6",
      "Gen 7",
      "Gen 8",
      "Gen 9",
    ],
  },
];
